package software.chronicle;

import jdk.internal.org.objectweb.asm.util.ASMifier;


public class StartHere {

    // 1. first dump the code of hello world
    public static void main(String[] args) throws Exception {
        ASMifier.main(new String[]{"software.chronicle.HelloWorld"});
    }

    // 2. first dump the code of hello world
    // runnign this generates some code, code this code into a new file, the modify the class name,
    // then generated byte code, run run this code.   - see HelloWorldDump for an example
}
